-- Resolver networks for test_tran_str
-- Auto-generated by gen_resolver.py
--
-- 54 nets needing resolution:
--   5 tran<->tran  (swap 'driver/'other)
--   49 assign+tran (regular driver + implicit)
--   3 leaf nets (no resolution)
--
-- Resolver is regular VHDL: reads driver signals, writes 'other signals.
-- For each endpoint i on a net: other(i) = resolve(all drivers except i)
--
-- NOTE: Regular assigns (ag <= a) also drive the std_logic net directly.
-- The tran entity's inout port currently drives 'U' (no normal driver).
-- Replumbing needed: either NVC uses 'driver as the port's actual driver,
-- or the assign is removed from the DUT and handled entirely by resolver.

-- ====================================================================
-- Net connectivity
-- ====================================================================
-- ac(1): assign(a) (supply1, supply0) <-> gen_chain(1).tc.a
-- ac(2): gen_chain(1).tc.b <-> gen_chain(2).tc.a
-- ac(3): gen_chain(2).tc.b <-> gen_chain(3).tc.a
-- ac(4): gen_chain(3).tc.b <-> gen_chain(4).tc.a
-- ac(5): gen_chain(4).tc.b <-> gen_chain(5).tc.a
-- ac(6): gen_chain(5).tc.b <-> gen_chain(6).tc.a
-- ag(1): assign(a) (supply1, supply0) <-> gen_row(1).gen_col(1).t_grid.a
-- bg(1): assign(b) (supply1, supply0) <-> gen_row(1).gen_col(1).t_grid.b
-- ag(2): assign(a) (supply1, strong0) <-> gen_row(1).gen_col(2).t_grid.a
-- bg(2): assign(b) (supply1, strong0) <-> gen_row(1).gen_col(2).t_grid.b
-- ag(3): assign(a) (supply1, pull0) <-> gen_row(1).gen_col(3).t_grid.a
-- bg(3): assign(b) (supply1, pull0) <-> gen_row(1).gen_col(3).t_grid.b
-- ag(4): assign(a) (supply1, weak0) <-> gen_row(1).gen_col(4).t_grid.a
-- bg(4): assign(b) (supply1, weak0) <-> gen_row(1).gen_col(4).t_grid.b
-- ag(5): assign(a) (supply1, highz0) <-> gen_row(1).gen_col(5).t_grid.a
-- bg(5): assign(b) (supply1, highz0) <-> gen_row(1).gen_col(5).t_grid.b
-- ag(6): assign(a) (strong1, supply0) <-> gen_row(2).gen_col(1).t_grid.a
-- bg(6): assign(b) (strong1, supply0) <-> gen_row(2).gen_col(1).t_grid.b
-- ag(7): assign(a) (strong1, strong0) <-> gen_row(2).gen_col(2).t_grid.a
-- bg(7): assign(b) (strong1, strong0) <-> gen_row(2).gen_col(2).t_grid.b
-- ag(8): assign(a) (strong1, pull0) <-> gen_row(2).gen_col(3).t_grid.a
-- bg(8): assign(b) (strong1, pull0) <-> gen_row(2).gen_col(3).t_grid.b
-- ag(9): assign(a) (strong1, weak0) <-> gen_row(2).gen_col(4).t_grid.a
-- bg(9): assign(b) (strong1, weak0) <-> gen_row(2).gen_col(4).t_grid.b
-- ag(10): assign(a) (strong1, highz0) <-> gen_row(2).gen_col(5).t_grid.a
-- bg(10): assign(b) (strong1, highz0) <-> gen_row(2).gen_col(5).t_grid.b
-- ag(11): assign(a) (pull1, supply0) <-> gen_row(3).gen_col(1).t_grid.a
-- bg(11): assign(b) (pull1, supply0) <-> gen_row(3).gen_col(1).t_grid.b
-- ag(12): assign(a) (pull1, strong0) <-> gen_row(3).gen_col(2).t_grid.a
-- bg(12): assign(b) (pull1, strong0) <-> gen_row(3).gen_col(2).t_grid.b
-- ag(13): assign(a) (pull1, pull0) <-> gen_row(3).gen_col(3).t_grid.a
-- bg(13): assign(b) (pull1, pull0) <-> gen_row(3).gen_col(3).t_grid.b
-- ag(14): assign(a) (pull1, weak0) <-> gen_row(3).gen_col(4).t_grid.a
-- bg(14): assign(b) (pull1, weak0) <-> gen_row(3).gen_col(4).t_grid.b
-- ag(15): assign(a) (pull1, highz0) <-> gen_row(3).gen_col(5).t_grid.a
-- bg(15): assign(b) (pull1, highz0) <-> gen_row(3).gen_col(5).t_grid.b
-- ag(16): assign(a) (weak1, supply0) <-> gen_row(4).gen_col(1).t_grid.a
-- bg(16): assign(b) (weak1, supply0) <-> gen_row(4).gen_col(1).t_grid.b
-- ag(17): assign(a) (weak1, strong0) <-> gen_row(4).gen_col(2).t_grid.a
-- bg(17): assign(b) (weak1, strong0) <-> gen_row(4).gen_col(2).t_grid.b
-- ag(18): assign(a) (weak1, pull0) <-> gen_row(4).gen_col(3).t_grid.a
-- bg(18): assign(b) (weak1, pull0) <-> gen_row(4).gen_col(3).t_grid.b
-- ag(19): assign(a) (weak1, weak0) <-> gen_row(4).gen_col(4).t_grid.a
-- bg(19): assign(b) (weak1, weak0) <-> gen_row(4).gen_col(4).t_grid.b
-- ag(20): assign(a) (weak1, highz0) <-> gen_row(4).gen_col(5).t_grid.a
-- bg(20): assign(b) (weak1, highz0) <-> gen_row(4).gen_col(5).t_grid.b
-- ag(21): assign(a) (highz1, supply0) <-> gen_row(5).gen_col(1).t_grid.a
-- bg(21): assign(b) (highz1, supply0) <-> gen_row(5).gen_col(1).t_grid.b
-- ag(22): assign(a) (highz1, strong0) <-> gen_row(5).gen_col(2).t_grid.a
-- bg(22): assign(b) (highz1, strong0) <-> gen_row(5).gen_col(2).t_grid.b
-- ag(23): assign(a) (highz1, pull0) <-> gen_row(5).gen_col(3).t_grid.a
-- bg(23): assign(b) (highz1, pull0) <-> gen_row(5).gen_col(3).t_grid.b
-- ag(24): assign(a) (highz1, weak0) <-> gen_row(5).gen_col(4).t_grid.a
-- bg(24): assign(b) (highz1, weak0) <-> gen_row(5).gen_col(4).t_grid.b

library ieee;
use ieee.std_logic_1164.all;
use work.logic3ds_pkg.all;

entity resolver_test_tran_str is
end entity;

architecture generated of resolver_test_tran_str is

    -- Source signals for regular assigns (read from DUT)
    alias src_a is << signal .resolved_test_tran_str.dut.a : std_logic >>;
    alias src_b is << signal .resolved_test_tran_str.dut.b : std_logic >>;

    -- Implicit signals inside tran instances
    -- drv_N = 'driver (what tran drives onto net)
    -- oth_N = 'other (what tran sees from all other drivers)
    -- ac(1): gen_chain(1).tc.a
    alias drv_0 is << signal .resolved_test_tran_str.dut.gen_chain(1).tc.a.driver : logic3ds >>;
    alias oth_0 is << signal .resolved_test_tran_str.dut.gen_chain(1).tc.a.other : logic3ds >>;
    -- ac(2): gen_chain(1).tc.b
    alias drv_1 is << signal .resolved_test_tran_str.dut.gen_chain(1).tc.b.driver : logic3ds >>;
    alias oth_1 is << signal .resolved_test_tran_str.dut.gen_chain(1).tc.b.other : logic3ds >>;
    -- ac(2): gen_chain(2).tc.a
    alias drv_2 is << signal .resolved_test_tran_str.dut.gen_chain(2).tc.a.driver : logic3ds >>;
    alias oth_2 is << signal .resolved_test_tran_str.dut.gen_chain(2).tc.a.other : logic3ds >>;
    -- ac(3): gen_chain(2).tc.b
    alias drv_3 is << signal .resolved_test_tran_str.dut.gen_chain(2).tc.b.driver : logic3ds >>;
    alias oth_3 is << signal .resolved_test_tran_str.dut.gen_chain(2).tc.b.other : logic3ds >>;
    -- ac(3): gen_chain(3).tc.a
    alias drv_4 is << signal .resolved_test_tran_str.dut.gen_chain(3).tc.a.driver : logic3ds >>;
    alias oth_4 is << signal .resolved_test_tran_str.dut.gen_chain(3).tc.a.other : logic3ds >>;
    -- ac(4): gen_chain(3).tc.b
    alias drv_5 is << signal .resolved_test_tran_str.dut.gen_chain(3).tc.b.driver : logic3ds >>;
    alias oth_5 is << signal .resolved_test_tran_str.dut.gen_chain(3).tc.b.other : logic3ds >>;
    -- ac(4): gen_chain(4).tc.a
    alias drv_6 is << signal .resolved_test_tran_str.dut.gen_chain(4).tc.a.driver : logic3ds >>;
    alias oth_6 is << signal .resolved_test_tran_str.dut.gen_chain(4).tc.a.other : logic3ds >>;
    -- ac(5): gen_chain(4).tc.b
    alias drv_7 is << signal .resolved_test_tran_str.dut.gen_chain(4).tc.b.driver : logic3ds >>;
    alias oth_7 is << signal .resolved_test_tran_str.dut.gen_chain(4).tc.b.other : logic3ds >>;
    -- ac(5): gen_chain(5).tc.a
    alias drv_8 is << signal .resolved_test_tran_str.dut.gen_chain(5).tc.a.driver : logic3ds >>;
    alias oth_8 is << signal .resolved_test_tran_str.dut.gen_chain(5).tc.a.other : logic3ds >>;
    -- ac(6): gen_chain(5).tc.b
    alias drv_9 is << signal .resolved_test_tran_str.dut.gen_chain(5).tc.b.driver : logic3ds >>;
    alias oth_9 is << signal .resolved_test_tran_str.dut.gen_chain(5).tc.b.other : logic3ds >>;
    -- ac(6): gen_chain(6).tc.a
    alias drv_10 is << signal .resolved_test_tran_str.dut.gen_chain(6).tc.a.driver : logic3ds >>;
    alias oth_10 is << signal .resolved_test_tran_str.dut.gen_chain(6).tc.a.other : logic3ds >>;
    -- ac(7): gen_chain(6).tc.b
    alias drv_11 is << signal .resolved_test_tran_str.dut.gen_chain(6).tc.b.driver : logic3ds >>;
    alias oth_11 is << signal .resolved_test_tran_str.dut.gen_chain(6).tc.b.other : logic3ds >>;
    -- ag(1): gen_row(1).gen_col(1).t_grid.a
    alias drv_12 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(1).t_grid.a.driver : logic3ds >>;
    alias oth_12 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(1).t_grid.a.other : logic3ds >>;
    -- bg(1): gen_row(1).gen_col(1).t_grid.b
    alias drv_13 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(1).t_grid.b.driver : logic3ds >>;
    alias oth_13 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(1).t_grid.b.other : logic3ds >>;
    -- ag(2): gen_row(1).gen_col(2).t_grid.a
    alias drv_14 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(2).t_grid.a.driver : logic3ds >>;
    alias oth_14 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(2).t_grid.a.other : logic3ds >>;
    -- bg(2): gen_row(1).gen_col(2).t_grid.b
    alias drv_15 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(2).t_grid.b.driver : logic3ds >>;
    alias oth_15 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(2).t_grid.b.other : logic3ds >>;
    -- ag(3): gen_row(1).gen_col(3).t_grid.a
    alias drv_16 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(3).t_grid.a.driver : logic3ds >>;
    alias oth_16 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(3).t_grid.a.other : logic3ds >>;
    -- bg(3): gen_row(1).gen_col(3).t_grid.b
    alias drv_17 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(3).t_grid.b.driver : logic3ds >>;
    alias oth_17 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(3).t_grid.b.other : logic3ds >>;
    -- ag(4): gen_row(1).gen_col(4).t_grid.a
    alias drv_18 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(4).t_grid.a.driver : logic3ds >>;
    alias oth_18 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(4).t_grid.a.other : logic3ds >>;
    -- bg(4): gen_row(1).gen_col(4).t_grid.b
    alias drv_19 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(4).t_grid.b.driver : logic3ds >>;
    alias oth_19 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(4).t_grid.b.other : logic3ds >>;
    -- ag(5): gen_row(1).gen_col(5).t_grid.a
    alias drv_20 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(5).t_grid.a.driver : logic3ds >>;
    alias oth_20 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(5).t_grid.a.other : logic3ds >>;
    -- bg(5): gen_row(1).gen_col(5).t_grid.b
    alias drv_21 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(5).t_grid.b.driver : logic3ds >>;
    alias oth_21 is << signal .resolved_test_tran_str.dut.gen_row(1).gen_col(5).t_grid.b.other : logic3ds >>;
    -- ag(6): gen_row(2).gen_col(1).t_grid.a
    alias drv_22 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(1).t_grid.a.driver : logic3ds >>;
    alias oth_22 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(1).t_grid.a.other : logic3ds >>;
    -- bg(6): gen_row(2).gen_col(1).t_grid.b
    alias drv_23 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(1).t_grid.b.driver : logic3ds >>;
    alias oth_23 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(1).t_grid.b.other : logic3ds >>;
    -- ag(7): gen_row(2).gen_col(2).t_grid.a
    alias drv_24 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(2).t_grid.a.driver : logic3ds >>;
    alias oth_24 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(2).t_grid.a.other : logic3ds >>;
    -- bg(7): gen_row(2).gen_col(2).t_grid.b
    alias drv_25 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(2).t_grid.b.driver : logic3ds >>;
    alias oth_25 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(2).t_grid.b.other : logic3ds >>;
    -- ag(8): gen_row(2).gen_col(3).t_grid.a
    alias drv_26 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(3).t_grid.a.driver : logic3ds >>;
    alias oth_26 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(3).t_grid.a.other : logic3ds >>;
    -- bg(8): gen_row(2).gen_col(3).t_grid.b
    alias drv_27 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(3).t_grid.b.driver : logic3ds >>;
    alias oth_27 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(3).t_grid.b.other : logic3ds >>;
    -- ag(9): gen_row(2).gen_col(4).t_grid.a
    alias drv_28 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(4).t_grid.a.driver : logic3ds >>;
    alias oth_28 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(4).t_grid.a.other : logic3ds >>;
    -- bg(9): gen_row(2).gen_col(4).t_grid.b
    alias drv_29 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(4).t_grid.b.driver : logic3ds >>;
    alias oth_29 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(4).t_grid.b.other : logic3ds >>;
    -- ag(10): gen_row(2).gen_col(5).t_grid.a
    alias drv_30 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(5).t_grid.a.driver : logic3ds >>;
    alias oth_30 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(5).t_grid.a.other : logic3ds >>;
    -- bg(10): gen_row(2).gen_col(5).t_grid.b
    alias drv_31 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(5).t_grid.b.driver : logic3ds >>;
    alias oth_31 is << signal .resolved_test_tran_str.dut.gen_row(2).gen_col(5).t_grid.b.other : logic3ds >>;
    -- ag(11): gen_row(3).gen_col(1).t_grid.a
    alias drv_32 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(1).t_grid.a.driver : logic3ds >>;
    alias oth_32 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(1).t_grid.a.other : logic3ds >>;
    -- bg(11): gen_row(3).gen_col(1).t_grid.b
    alias drv_33 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(1).t_grid.b.driver : logic3ds >>;
    alias oth_33 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(1).t_grid.b.other : logic3ds >>;
    -- ag(12): gen_row(3).gen_col(2).t_grid.a
    alias drv_34 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(2).t_grid.a.driver : logic3ds >>;
    alias oth_34 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(2).t_grid.a.other : logic3ds >>;
    -- bg(12): gen_row(3).gen_col(2).t_grid.b
    alias drv_35 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(2).t_grid.b.driver : logic3ds >>;
    alias oth_35 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(2).t_grid.b.other : logic3ds >>;
    -- ag(13): gen_row(3).gen_col(3).t_grid.a
    alias drv_36 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(3).t_grid.a.driver : logic3ds >>;
    alias oth_36 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(3).t_grid.a.other : logic3ds >>;
    -- bg(13): gen_row(3).gen_col(3).t_grid.b
    alias drv_37 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(3).t_grid.b.driver : logic3ds >>;
    alias oth_37 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(3).t_grid.b.other : logic3ds >>;
    -- ag(14): gen_row(3).gen_col(4).t_grid.a
    alias drv_38 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(4).t_grid.a.driver : logic3ds >>;
    alias oth_38 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(4).t_grid.a.other : logic3ds >>;
    -- bg(14): gen_row(3).gen_col(4).t_grid.b
    alias drv_39 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(4).t_grid.b.driver : logic3ds >>;
    alias oth_39 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(4).t_grid.b.other : logic3ds >>;
    -- ag(15): gen_row(3).gen_col(5).t_grid.a
    alias drv_40 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(5).t_grid.a.driver : logic3ds >>;
    alias oth_40 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(5).t_grid.a.other : logic3ds >>;
    -- bg(15): gen_row(3).gen_col(5).t_grid.b
    alias drv_41 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(5).t_grid.b.driver : logic3ds >>;
    alias oth_41 is << signal .resolved_test_tran_str.dut.gen_row(3).gen_col(5).t_grid.b.other : logic3ds >>;
    -- ag(16): gen_row(4).gen_col(1).t_grid.a
    alias drv_42 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(1).t_grid.a.driver : logic3ds >>;
    alias oth_42 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(1).t_grid.a.other : logic3ds >>;
    -- bg(16): gen_row(4).gen_col(1).t_grid.b
    alias drv_43 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(1).t_grid.b.driver : logic3ds >>;
    alias oth_43 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(1).t_grid.b.other : logic3ds >>;
    -- ag(17): gen_row(4).gen_col(2).t_grid.a
    alias drv_44 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(2).t_grid.a.driver : logic3ds >>;
    alias oth_44 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(2).t_grid.a.other : logic3ds >>;
    -- bg(17): gen_row(4).gen_col(2).t_grid.b
    alias drv_45 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(2).t_grid.b.driver : logic3ds >>;
    alias oth_45 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(2).t_grid.b.other : logic3ds >>;
    -- ag(18): gen_row(4).gen_col(3).t_grid.a
    alias drv_46 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(3).t_grid.a.driver : logic3ds >>;
    alias oth_46 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(3).t_grid.a.other : logic3ds >>;
    -- bg(18): gen_row(4).gen_col(3).t_grid.b
    alias drv_47 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(3).t_grid.b.driver : logic3ds >>;
    alias oth_47 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(3).t_grid.b.other : logic3ds >>;
    -- ag(19): gen_row(4).gen_col(4).t_grid.a
    alias drv_48 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(4).t_grid.a.driver : logic3ds >>;
    alias oth_48 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(4).t_grid.a.other : logic3ds >>;
    -- bg(19): gen_row(4).gen_col(4).t_grid.b
    alias drv_49 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(4).t_grid.b.driver : logic3ds >>;
    alias oth_49 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(4).t_grid.b.other : logic3ds >>;
    -- ag(20): gen_row(4).gen_col(5).t_grid.a
    alias drv_50 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(5).t_grid.a.driver : logic3ds >>;
    alias oth_50 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(5).t_grid.a.other : logic3ds >>;
    -- bg(20): gen_row(4).gen_col(5).t_grid.b
    alias drv_51 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(5).t_grid.b.driver : logic3ds >>;
    alias oth_51 is << signal .resolved_test_tran_str.dut.gen_row(4).gen_col(5).t_grid.b.other : logic3ds >>;
    -- ag(21): gen_row(5).gen_col(1).t_grid.a
    alias drv_52 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(1).t_grid.a.driver : logic3ds >>;
    alias oth_52 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(1).t_grid.a.other : logic3ds >>;
    -- bg(21): gen_row(5).gen_col(1).t_grid.b
    alias drv_53 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(1).t_grid.b.driver : logic3ds >>;
    alias oth_53 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(1).t_grid.b.other : logic3ds >>;
    -- ag(22): gen_row(5).gen_col(2).t_grid.a
    alias drv_54 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(2).t_grid.a.driver : logic3ds >>;
    alias oth_54 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(2).t_grid.a.other : logic3ds >>;
    -- bg(22): gen_row(5).gen_col(2).t_grid.b
    alias drv_55 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(2).t_grid.b.driver : logic3ds >>;
    alias oth_55 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(2).t_grid.b.other : logic3ds >>;
    -- ag(23): gen_row(5).gen_col(3).t_grid.a
    alias drv_56 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(3).t_grid.a.driver : logic3ds >>;
    alias oth_56 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(3).t_grid.a.other : logic3ds >>;
    -- bg(23): gen_row(5).gen_col(3).t_grid.b
    alias drv_57 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(3).t_grid.b.driver : logic3ds >>;
    alias oth_57 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(3).t_grid.b.other : logic3ds >>;
    -- ag(24): gen_row(5).gen_col(4).t_grid.a
    alias drv_58 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(4).t_grid.a.driver : logic3ds >>;
    alias oth_58 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(4).t_grid.a.other : logic3ds >>;
    -- bg(24): gen_row(5).gen_col(4).t_grid.b
    alias drv_59 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(4).t_grid.b.driver : logic3ds >>;
    alias oth_59 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(4).t_grid.b.other : logic3ds >>;
    -- ag(25): gen_row(5).gen_col(5).t_grid.a
    alias drv_60 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(5).t_grid.a.driver : logic3ds >>;
    alias oth_60 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(5).t_grid.a.other : logic3ds >>;
    -- bg(25): gen_row(5).gen_col(5).t_grid.b
    alias drv_61 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(5).t_grid.b.driver : logic3ds >>;
    alias oth_61 is << signal .resolved_test_tran_str.dut.gen_row(5).gen_col(5).t_grid.b.other : logic3ds >>;

    -- Convert std_logic to logic3ds with asymmetric strengths
    -- Models Verilog: assign (str1, str0) y = d;
    function to_logic3ds_asym(
        val : std_logic; str1, str0 : l3ds_strength
    ) return logic3ds is
    begin
        case val is
            when '1' | 'H' => return l3ds_drive(true, str1);
            when '0' | 'L' => return l3ds_drive(false, str0);
            when 'Z'       => return L3DS_Z;
            when others     =>
                if str_gt(str1, str0) then
                    return make_logic3ds(0, str1, FL_UNKNOWN);
                else
                    return make_logic3ds(0, str0, FL_UNKNOWN);
                end if;
        end case;
    end function;

begin

    ---------------------------------------------------------------
    -- tran <-> tran: swap 'driver/'other
    ---------------------------------------------------------------
    -- ac(2): gen_chain(1).tc.b <-> gen_chain(2).tc.a
    oth_1 <= drv_2;
    oth_2 <= drv_1;

    -- ac(3): gen_chain(2).tc.b <-> gen_chain(3).tc.a
    oth_3 <= drv_4;
    oth_4 <= drv_3;

    -- ac(4): gen_chain(3).tc.b <-> gen_chain(4).tc.a
    oth_5 <= drv_6;
    oth_6 <= drv_5;

    -- ac(5): gen_chain(4).tc.b <-> gen_chain(5).tc.a
    oth_7 <= drv_8;
    oth_8 <= drv_7;

    -- ac(6): gen_chain(5).tc.b <-> gen_chain(6).tc.a
    oth_9 <= drv_10;
    oth_10 <= drv_9;

    ---------------------------------------------------------------
    -- assign + tran: regular driver feeds tran 'other
    ---------------------------------------------------------------
    -- ac(1): assign(a) (supply1, supply0) -> gen_chain(1).tc.a
    oth_0 <= to_logic3ds_asym(src_a, ST_SUPPLY, ST_SUPPLY);

    -- ag(1): assign(a) (supply1, supply0) -> gen_row(1).gen_col(1).t_grid.a
    oth_12 <= to_logic3ds_asym(src_a, ST_SUPPLY, ST_SUPPLY);

    -- bg(1): assign(b) (supply1, supply0) -> gen_row(1).gen_col(1).t_grid.b
    oth_13 <= to_logic3ds_asym(src_b, ST_SUPPLY, ST_SUPPLY);

    -- ag(2): assign(a) (supply1, strong0) -> gen_row(1).gen_col(2).t_grid.a
    oth_14 <= to_logic3ds_asym(src_a, ST_SUPPLY, ST_STRONG);

    -- bg(2): assign(b) (supply1, strong0) -> gen_row(1).gen_col(2).t_grid.b
    oth_15 <= to_logic3ds_asym(src_b, ST_SUPPLY, ST_STRONG);

    -- ag(3): assign(a) (supply1, pull0) -> gen_row(1).gen_col(3).t_grid.a
    oth_16 <= to_logic3ds_asym(src_a, ST_SUPPLY, ST_PULL);

    -- bg(3): assign(b) (supply1, pull0) -> gen_row(1).gen_col(3).t_grid.b
    oth_17 <= to_logic3ds_asym(src_b, ST_SUPPLY, ST_PULL);

    -- ag(4): assign(a) (supply1, weak0) -> gen_row(1).gen_col(4).t_grid.a
    oth_18 <= to_logic3ds_asym(src_a, ST_SUPPLY, ST_WEAK);

    -- bg(4): assign(b) (supply1, weak0) -> gen_row(1).gen_col(4).t_grid.b
    oth_19 <= to_logic3ds_asym(src_b, ST_SUPPLY, ST_WEAK);

    -- ag(5): assign(a) (supply1, highz0) -> gen_row(1).gen_col(5).t_grid.a
    oth_20 <= to_logic3ds_asym(src_a, ST_SUPPLY, ST_HIGHZ);

    -- bg(5): assign(b) (supply1, highz0) -> gen_row(1).gen_col(5).t_grid.b
    oth_21 <= to_logic3ds_asym(src_b, ST_SUPPLY, ST_HIGHZ);

    -- ag(6): assign(a) (strong1, supply0) -> gen_row(2).gen_col(1).t_grid.a
    oth_22 <= to_logic3ds_asym(src_a, ST_STRONG, ST_SUPPLY);

    -- bg(6): assign(b) (strong1, supply0) -> gen_row(2).gen_col(1).t_grid.b
    oth_23 <= to_logic3ds_asym(src_b, ST_STRONG, ST_SUPPLY);

    -- ag(7): assign(a) (strong1, strong0) -> gen_row(2).gen_col(2).t_grid.a
    oth_24 <= to_logic3ds_asym(src_a, ST_STRONG, ST_STRONG);

    -- bg(7): assign(b) (strong1, strong0) -> gen_row(2).gen_col(2).t_grid.b
    oth_25 <= to_logic3ds_asym(src_b, ST_STRONG, ST_STRONG);

    -- ag(8): assign(a) (strong1, pull0) -> gen_row(2).gen_col(3).t_grid.a
    oth_26 <= to_logic3ds_asym(src_a, ST_STRONG, ST_PULL);

    -- bg(8): assign(b) (strong1, pull0) -> gen_row(2).gen_col(3).t_grid.b
    oth_27 <= to_logic3ds_asym(src_b, ST_STRONG, ST_PULL);

    -- ag(9): assign(a) (strong1, weak0) -> gen_row(2).gen_col(4).t_grid.a
    oth_28 <= to_logic3ds_asym(src_a, ST_STRONG, ST_WEAK);

    -- bg(9): assign(b) (strong1, weak0) -> gen_row(2).gen_col(4).t_grid.b
    oth_29 <= to_logic3ds_asym(src_b, ST_STRONG, ST_WEAK);

    -- ag(10): assign(a) (strong1, highz0) -> gen_row(2).gen_col(5).t_grid.a
    oth_30 <= to_logic3ds_asym(src_a, ST_STRONG, ST_HIGHZ);

    -- bg(10): assign(b) (strong1, highz0) -> gen_row(2).gen_col(5).t_grid.b
    oth_31 <= to_logic3ds_asym(src_b, ST_STRONG, ST_HIGHZ);

    -- ag(11): assign(a) (pull1, supply0) -> gen_row(3).gen_col(1).t_grid.a
    oth_32 <= to_logic3ds_asym(src_a, ST_PULL, ST_SUPPLY);

    -- bg(11): assign(b) (pull1, supply0) -> gen_row(3).gen_col(1).t_grid.b
    oth_33 <= to_logic3ds_asym(src_b, ST_PULL, ST_SUPPLY);

    -- ag(12): assign(a) (pull1, strong0) -> gen_row(3).gen_col(2).t_grid.a
    oth_34 <= to_logic3ds_asym(src_a, ST_PULL, ST_STRONG);

    -- bg(12): assign(b) (pull1, strong0) -> gen_row(3).gen_col(2).t_grid.b
    oth_35 <= to_logic3ds_asym(src_b, ST_PULL, ST_STRONG);

    -- ag(13): assign(a) (pull1, pull0) -> gen_row(3).gen_col(3).t_grid.a
    oth_36 <= to_logic3ds_asym(src_a, ST_PULL, ST_PULL);

    -- bg(13): assign(b) (pull1, pull0) -> gen_row(3).gen_col(3).t_grid.b
    oth_37 <= to_logic3ds_asym(src_b, ST_PULL, ST_PULL);

    -- ag(14): assign(a) (pull1, weak0) -> gen_row(3).gen_col(4).t_grid.a
    oth_38 <= to_logic3ds_asym(src_a, ST_PULL, ST_WEAK);

    -- bg(14): assign(b) (pull1, weak0) -> gen_row(3).gen_col(4).t_grid.b
    oth_39 <= to_logic3ds_asym(src_b, ST_PULL, ST_WEAK);

    -- ag(15): assign(a) (pull1, highz0) -> gen_row(3).gen_col(5).t_grid.a
    oth_40 <= to_logic3ds_asym(src_a, ST_PULL, ST_HIGHZ);

    -- bg(15): assign(b) (pull1, highz0) -> gen_row(3).gen_col(5).t_grid.b
    oth_41 <= to_logic3ds_asym(src_b, ST_PULL, ST_HIGHZ);

    -- ag(16): assign(a) (weak1, supply0) -> gen_row(4).gen_col(1).t_grid.a
    oth_42 <= to_logic3ds_asym(src_a, ST_WEAK, ST_SUPPLY);

    -- bg(16): assign(b) (weak1, supply0) -> gen_row(4).gen_col(1).t_grid.b
    oth_43 <= to_logic3ds_asym(src_b, ST_WEAK, ST_SUPPLY);

    -- ag(17): assign(a) (weak1, strong0) -> gen_row(4).gen_col(2).t_grid.a
    oth_44 <= to_logic3ds_asym(src_a, ST_WEAK, ST_STRONG);

    -- bg(17): assign(b) (weak1, strong0) -> gen_row(4).gen_col(2).t_grid.b
    oth_45 <= to_logic3ds_asym(src_b, ST_WEAK, ST_STRONG);

    -- ag(18): assign(a) (weak1, pull0) -> gen_row(4).gen_col(3).t_grid.a
    oth_46 <= to_logic3ds_asym(src_a, ST_WEAK, ST_PULL);

    -- bg(18): assign(b) (weak1, pull0) -> gen_row(4).gen_col(3).t_grid.b
    oth_47 <= to_logic3ds_asym(src_b, ST_WEAK, ST_PULL);

    -- ag(19): assign(a) (weak1, weak0) -> gen_row(4).gen_col(4).t_grid.a
    oth_48 <= to_logic3ds_asym(src_a, ST_WEAK, ST_WEAK);

    -- bg(19): assign(b) (weak1, weak0) -> gen_row(4).gen_col(4).t_grid.b
    oth_49 <= to_logic3ds_asym(src_b, ST_WEAK, ST_WEAK);

    -- ag(20): assign(a) (weak1, highz0) -> gen_row(4).gen_col(5).t_grid.a
    oth_50 <= to_logic3ds_asym(src_a, ST_WEAK, ST_HIGHZ);

    -- bg(20): assign(b) (weak1, highz0) -> gen_row(4).gen_col(5).t_grid.b
    oth_51 <= to_logic3ds_asym(src_b, ST_WEAK, ST_HIGHZ);

    -- ag(21): assign(a) (highz1, supply0) -> gen_row(5).gen_col(1).t_grid.a
    oth_52 <= to_logic3ds_asym(src_a, ST_HIGHZ, ST_SUPPLY);

    -- bg(21): assign(b) (highz1, supply0) -> gen_row(5).gen_col(1).t_grid.b
    oth_53 <= to_logic3ds_asym(src_b, ST_HIGHZ, ST_SUPPLY);

    -- ag(22): assign(a) (highz1, strong0) -> gen_row(5).gen_col(2).t_grid.a
    oth_54 <= to_logic3ds_asym(src_a, ST_HIGHZ, ST_STRONG);

    -- bg(22): assign(b) (highz1, strong0) -> gen_row(5).gen_col(2).t_grid.b
    oth_55 <= to_logic3ds_asym(src_b, ST_HIGHZ, ST_STRONG);

    -- ag(23): assign(a) (highz1, pull0) -> gen_row(5).gen_col(3).t_grid.a
    oth_56 <= to_logic3ds_asym(src_a, ST_HIGHZ, ST_PULL);

    -- bg(23): assign(b) (highz1, pull0) -> gen_row(5).gen_col(3).t_grid.b
    oth_57 <= to_logic3ds_asym(src_b, ST_HIGHZ, ST_PULL);

    -- ag(24): assign(a) (highz1, weak0) -> gen_row(5).gen_col(4).t_grid.a
    oth_58 <= to_logic3ds_asym(src_a, ST_HIGHZ, ST_WEAK);

    -- bg(24): assign(b) (highz1, weak0) -> gen_row(5).gen_col(4).t_grid.b
    oth_59 <= to_logic3ds_asym(src_b, ST_HIGHZ, ST_WEAK);

end architecture;

-- Wrapper: instantiates DUT + resolver for standalone simulation
library ieee;
use ieee.std_logic_1164.all;

entity resolved_test_tran_str is end;
architecture wrapper of resolved_test_tran_str is
begin
    dut: entity work.test_tran_str;
    resolver: entity work.resolver_test_tran_str;
end architecture;
