"""
federation_resolver.py -- the federation-specific bits that sit OUTSIDE the
resolver-net code-generator.

The per-net VHDL (tapping a DUT-top boundary net and wiring it to the peer via
fed_put/fed_get/fed_eval) is generated by sv2vhdl_resolver._gen_fed_vhdl, reusing
all of that module's machinery (external-name aliasing, wrapper, hashing). This
file holds only what's genuinely new:

  * gen_dummy_dut()   -- the Verilog stub the Verilator TB instantiates in place
                         of the real DUT (its ports are the bridge tap points).
  * federation_pkg()  -- the VHDL package of bridge foreign functions
                         (fed_eval / fed_put / fed_get), implemented by
                         libfederation_bridge.so which hosts the Verilator peer.

Topology (one nvc process): real DUT <-> _gen_fed_vhdl resolver <-> bridge .so
<-> Verilator TB + dummy DUT.
"""


def _vlog_range(width):
    return "" if width <= 1 else f"[{width - 1}:0] "


def gen_dummy_dut(module_name, ports):
    """Verilog stub with the same ports as the real DUT, no logic. The Verilator
    TB instantiates this; the bridge harness peeks the stub's inputs (driven by
    the TB -> forwarded to nvc) and pokes its outputs (from nvc). Ports are
    exposed verilator-public for the C++ harness.

    ports : [{"name", "dir": "in"|"out", "width"}]
    """
    decl = [f"    {'input' if p['dir']=='in' else 'output'} wire "
            f"{_vlog_range(p['width'])}{p['name']}" for p in ports]
    body = []
    for p in ports:
        rng = _vlog_range(p["width"])
        if p["dir"] == "in":
            # TB drives this; bridge reads _pub_x and forwards to the real DUT
            body.append(f"    wire {rng}_pub_{p['name']} /* verilator public_flat_rw */;")
            body.append(f"    assign _pub_{p['name']} = {p['name']};")
        else:
            # bridge pokes _drv_x from the real DUT's output; TB reads the port
            body.append(f"    reg {rng}_drv_{p['name']} /* verilator public_flat_rw */;")
            body.append(f"    assign {p['name']} = _drv_{p['name']};")
    return "\n".join([
        f"// federation dummy DUT for {module_name}: same interface, no logic.",
        f"// Inputs exposed (TB drives -> bridge reads -> real DUT); outputs driven",
        f"// by public regs the bridge pokes from the real DUT. Real logic is federated.",
        f"module {module_name} (",
        ",\n".join(decl),
        ");",
        *body,
        "endmodule",
    ])


def federation_pkg():
    """VHDL package of bridge foreign functions + the fed_tick re-arm signal.
    Integer ABI: signals are addressed by an integer net-index (matched by the
    bridge's generated name table), values are integers — so the VHPIDIRECT
    boundary is pure-integer (no string/std_logic_vector ABI). slv<->int
    conversion happens in the per-net resolver (numeric_std). Implemented by
    libfederation_bridge.so."""
    return "\n".join([
        "-- Federation bridge foreign functions (libfederation_bridge.so hosts",
        "-- the Verilator peer model and steps it). Integer ABI.",
        "library ieee; use ieee.std_logic_1164.all;",
        "",
        "package federation_pkg is",
        "    signal fed_tick : std_logic := '0';   -- bridge toggles per peer delta",
        "    procedure fed_eval;",
        "    procedure fed_put(idx : in integer; val : in integer);",
        "    impure function fed_get(idx : integer) return integer;",
        "end package;",
        "",
        "package body federation_pkg is",
        "    procedure fed_eval is",
        '        attribute foreign of fed_eval : procedure is "VHPIDIRECT fed_eval";',
        "    begin end procedure;",
        "    procedure fed_put(idx : in integer; val : in integer) is",
        '        attribute foreign of fed_put : procedure is "VHPIDIRECT fed_put";',
        "    begin end procedure;",
        "    impure function fed_get(idx : integer) return integer is",
        '        attribute foreign of fed_get : function is "VHPIDIRECT fed_get";',
        "    begin end function;",
        "end package body;",
    ])


def _vhdl_type(width):
    return "std_logic" if width <= 1 else f"std_logic_vector({width - 1} downto 0)"


def federation_nets(dut_path, ports):
    """NET FLAGGING: build resolver net dicts for the DUT-top boundary ports,
    each carrying the "federation" key so sv2vhdl_resolver._gen_fed_vhdl fires.
    The net index (position here) is the integer the resolver/bridge use to
    address the signal — keep it in lockstep with gen_names_header(ports).

    In federation mode the resolver plugin calls this with the DUT instance path
    + its port list, then feeds the result to resolve_net() instead of (or
    alongside) the auto-discovered multi-driver nets.

    ports : [{"name", "dir": "in"|"out", "width"}]
    """
    nets = []
    for p in ports:
        ename = f"{dut_path}.{p['name']}"
        t = _vhdl_type(p["width"])
        nets.append({
            "net_name": p["name"],
            "drivers":   [{"ename": ename, "type": t}],
            "receivers": [{"ename": ename, "type": t}],
            "init_value": "0",
            "federation": {"dir": p["dir"], "peer": p["name"]},
        })
    return nets


def gen_names_header(ports):
    """C header for the bridge: index -> peer VPI signal name, in the SAME order
    as federation_nets(ports) (so the integer net-index matches). Included by
    libfederation_bridge.cpp (-DFED_NAMES_HEADER) at the per-design build."""
    rows = ",\n".join(f'    "{p["name"]}"' for p in ports)
    return (
        "/* auto-generated: federation net-index -> peer VPI signal name.\n"
        "   The bridge prefixes with the peer hierarchy (TOP.<dut>.) at lookup. */\n"
        f"static const char *fed_names[] = {{\n{rows}\n}};\n"
        f"static const int   fed_nnames = {len(ports)};\n"
    )


if __name__ == "__main__":
    import sv2vhdl_resolver as R
    ports = [
        {"name": "clk", "dir": "in", "width": 1},
        {"name": "a_data", "dir": "in", "width": 4},
        {"name": "sum_valid", "dir": "out", "width": 1},
        {"name": "sum_data", "dir": "out", "width": 4},
    ]
    print("=== dummy DUT (Verilator side) ===")
    print(gen_dummy_dut("a_plus_b_using_wrapped_fifos", ports))
    print("\n=== federation_pkg (nvc side) ===")
    print(federation_pkg())
    print("\n=== per-net federation resolver (via sv2vhdl_resolver._gen_fed_vhdl) ===")
    for i, p in enumerate(ports):
        net = {
            "net_name": p["name"],
            "drivers":   [{"ename": f"TOP.DUT.{p['name']}", "type": "std_logic" if p["width"] == 1 else f"std_logic_vector({p['width']-1} downto 0)"}],
            "receivers": [{"ename": f"TOP.DUT.{p['name']}", "type": "std_logic" if p["width"] == 1 else f"std_logic_vector({p['width']-1} downto 0)"}],
            "federation": {"dir": p["dir"], "peer": p["name"]},
        }
        name, vhd = R._gen_fed_vhdl(net, i, "a_plus_b", lambda e: e)
        print(f"\n---- {name} ----\n{vhd}")
